#ifndef _CPUEMU_CONFIG_H_
#define _CPUEMU_CONFIG_H_

/*
 * symbol table config
 */
#define CPUEMU_CONFIG_FUNC_SYMBOL_TABLE_NUM		1024
#define CPUEMU_CONFIG_OBJECT_SYMBOL_TABLE_NUM	1024

#endif /* _CPUEMU_CONFIG_H_ */
